# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20160211_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independent',
            name='imageFileUrl',
            field=models.CharField(blank=True, default=b'', max_length=1000),
        ),
    ]
