# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20160211_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='independent',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='independent',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='independent',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
