# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='price',
            field=models.BigIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='status',
            field=models.IntegerField(choices=[(1, b'IN_PROGRESS'), (2, b'AVAILABLE')], default=1),
            preserve_default=False,
        ),
    ]
