# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20160221_1753'),
        ('hello', '0006_auto_20160221_1952'),
    ]

    operations = [
    ]
