# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
